# Tests for different classes #

Test for methods of the Layer classes

In [11]:
from Layers.Layers import MSALinearLayer, ReluLayer
from Networks.ResNet import ConvNet, FCNet
import numpy as np 
import pandas as pd
import random
import os
import torch
import torch.nn as nn
import torch.nn.functional as F

layer = MSALinearLayer(in_features=3, out_features=4, test=True)

Parameter containing:
tensor([[-1.,  1., -1.],
        [ 1., -1.,  1.],
        [-1.,  1., -1.],
        [ 1., -1.,  1.]], dtype=torch.float64, requires_grad=True)


In [4]:
def forward_test():
    x = torch.tensor([1,2,3], dtype=torch.float64)
    res = layer.forward(x)
    print(res)
    goal = torch.tensor([-2,2,-2,2], dtype=torch.float64)
    print(goal)
    
forward_test()

tensor([-2.,  2., -2.,  2.], dtype=torch.float64, grad_fn=<SqueezeBackward3>)
tensor([-2.,  2., -2.,  2.], dtype=torch.float64)


In [2]:
def hamilton_test():
    x = torch.tensor([1,2,3], dtype=torch.float64, requires_grad=True)
    lambd = torch.tensor([1,2,3,4], dtype=torch.float64)
    res = layer.hamilton(x,lambd)
    print(res)
    goal = 4
    print(goal)
    res.backward()
    print(x.grad)
    goal = [2, -2, 2]
    print(goal)
hamilton_test()

tensor(4., dtype=torch.float64, grad_fn=<DotBackward>)
4
tensor([ 2., -2.,  2.], dtype=torch.float64)
[2, -2, 2]


In [9]:
def gen_dict(name, elements, layer_index):
    res_dict = {}
    for i in range(len(elements)):
        dict_key = name+'_batch'+str(i)+'FC'+str(layer_index)
        res_dict.update({dict_key:torch.tensor(elements[i], dtype=torch.float64)})
    return res_dict
    

def set_weights_test_1():
    layer_index = 1
    batch_size = 2
    x_dict = gen_dict('x', [[1,2,3],[2,3,0]], layer_index)
    lambda_dict = gen_dict('lambda', [[1,2,3,4],[4,1,3,2]], layer_index+1)
    layer.set_weights(layer_index, x_dict, lambda_dict, batch_size)
    goal_m = torch.tensor([[9,14,3],[4,7,6],[9,15,9],[8,14,12]])
    print(goal_m)
    print(layer.linear.weight)
    goal = torch.tensor([[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
    print(goal)
    
    

def set_weights_test_2():
    layer_index = 1
    batch_size = 2
    x_dict = gen_dict('x', [[1,2,3],[2,3,0]], layer_index)
    lambda_dict = gen_dict('lambda', [[0,-2,1,-3],[-1,-2,3,-4]], layer_index+1)
    layer.set_weights(layer_index, x_dict, lambda_dict, batch_size)
    goal_m = torch.tensor([[-2,-3,0],[-6,-10,-6],[7,11,3],[-11,-18,-9]])
    print(torch.max(goal_m))
    print(goal_m)
    print(layer.linear.weight)
    goal = torch.tensor([[-1,-1,1],[-1,-1,-1],[1,1,1],[-1,-1,-1]])
    print(goal)
    
set_weights_test_1()

set_weights_test_2()

{'x_batch0FC1': tensor([1., 2., 3.], dtype=torch.float64), 'x_batch1FC1': tensor([2., 3., 0.], dtype=torch.float64)}
{'lambda_batch0FC2': tensor([1., 2., 3., 4.], dtype=torch.float64), 'lambda_batch1FC2': tensor([4., 1., 3., 2.], dtype=torch.float64)}
tensor([[4.5000, 7.0000, 1.5000],
        [2.0000, 3.5000, 3.0000],
        [4.5000, 7.5000, 4.5000],
        [4.0000, 7.0000, 6.0000]], dtype=torch.float64)
tensor([[ 9, 14,  3],
        [ 4,  7,  6],
        [ 9, 15,  9],
        [ 8, 14, 12]])
Parameter containing:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64, requires_grad=True)
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
{'x_batch0FC1': tensor([1., 2., 3.], dtype=torch.float64), 'x_batch1FC1': tensor([2., 3., 0.], dtype=torch.float64)}
{'lambda_batch0FC2': tensor([ 0., -2.,  1., -3.], dtype=torch.float64), 'lambda_batch1FC2': tensor([-1., -2.,  3., -4.], dtype=torch.float64)}
tensor([[-1.

Tests for methods of the ConvNet classes

In [2]:
net = FCNet(num_fc=2,sizes_fc=[3,4,2], test=True)

Parameter containing:
tensor([[-1.,  1., -1.],
        [ 1., -1.,  1.],
        [-1.,  1., -1.],
        [ 1., -1.,  1.]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-1.,  1., -1.,  1.],
        [ 1., -1.,  1., -1.]], dtype=torch.float64, requires_grad=True)


In [3]:
def forward_test():
    x_test = torch.tensor([1,2,3], dtype=torch.float64)
    net.batch_element = 1
    net.forward(x_test)
    print(net.x_dict)
    
forward_test()

C:\Users\pscha\Documents\GitHub\OC-Methods-for-DL\Networks\ResNet.py:339: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x_dict.update({x_key:torch.tensor(x, requires_grad=True)})
C:\Users\pscha\Documents\GitHub\OC-Methods-for-DL\Networks\ResNet.py:342: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x_dict.update({x_key:torch.tensor(x, requires_grad=True)})


{'x_batch1FC0': tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True), 'x_batch1FC1': tensor([-2.,  2., -2.,  2.], dtype=torch.float64, requires_grad=True), 'x_batch1FC2': tensor([0., 2., 0., 2.], dtype=torch.float64, requires_grad=True), 'x_batch1FC3': tensor([ 4., -4.], dtype=torch.float64, requires_grad=True)}


In [4]:
def single_iteration_test():
    x_test_1 = torch.tensor([1,2,3], dtype=torch.float64)
    label_test_1 = torch.tensor([1,0])
    x_test_2 = torch.tensor([3,1,2], dtype=torch.float64)
    criterion = nn.CrossEntropyLoss()
    net.batch_element = 0
    net.msa_step_1(x_test_1)
    net.msa_step_2(criterion, label_test_1)
    net.batch_element = 1
    net.msa_step_1(x_test_2)
    net.msa_step_2(criterion, label_test_1)
    net.msa_step_3(2)
    print(net.forward(x_test_1))
    print(net.forward(x_test_2))
single_iteration_test()

C:\Users\pscha\Documents\GitHub\OC-Methods-for-DL\Networks\ResNet.py:339: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x_dict.update({x_key:torch.tensor(x, requires_grad=True)})
C:\Users\pscha\Documents\GitHub\OC-Methods-for-DL\Networks\ResNet.py:342: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x_dict.update({x_key:torch.tensor(x, requires_grad=True)})


{'x_batch1FC0': tensor([3., 1., 2.], dtype=torch.float64, requires_grad=True), 'x_batch1FC1': tensor([-4.,  4., -4.,  4.], dtype=torch.float64, requires_grad=True), 'x_batch1FC2': tensor([0., 4., 0., 4.], dtype=torch.float64, requires_grad=True), 'x_batch1FC3': tensor([ 8., -8.], dtype=torch.float64, requires_grad=True), 'x_batch0FC0': tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True), 'x_batch0FC1': tensor([-2.,  2., -2.,  2.], dtype=torch.float64, requires_grad=True), 'x_batch0FC2': tensor([0., 2., 0., 2.], dtype=torch.float64, requires_grad=True), 'x_batch0FC3': tensor([ 4., -4.], dtype=torch.float64, requires_grad=True)}
{'lambda_batch0FC3': tensor([-0.9997,  0.9997], dtype=torch.float64), 'lambda_batch0FC2': tensor([ 1.9993, -1.9993,  1.9993, -1.9993], dtype=torch.float64), 'lambda_batch0FC1': tensor([ 0.0000, -1.9993,  0.0000, -1.9993], dtype=torch.float64), 'lambda_batch0FC0': tensor([-3.9987,  3.9987, -3.9987], dtype=torch.float64), 'lambda_batch1FC3': tensor([ 1.12

In [10]:
x= torch.tensor([[1,2],[3,4]])
y= torch.tensor([[1,0],[0,1]])
print(x*y)

tensor([[1, 0],
        [0, 4]])


In [5]:
criterion = nn.CrossEntropyLoss()
x_res = torch.tensor([[4,-4]], dtype=torch.float64, requires_grad=True)
x_label = torch.tensor([1])
loss = criterion(x_res,x_label)
print(loss)
loss.backward()
print(x_res.grad)

tensor(8.0003, dtype=torch.float64, grad_fn=<NllLossBackward>)
tensor([[ 0.9997, -0.9997]], dtype=torch.float64)


In [ ]:
print

In [6]:
x_test = torch.tensor([-1,2,-3], dtype=torch.float64, requires_grad=True)
p_test = torch.tensor([1,2,3], dtype=torch.float64)
x_neu = F.relu(x_test)
print(x_neu)
H=torch.dot(x_neu,p_test)
print(H)
H.backward()
print(x_test.grad)

tensor([0., 2., 0.], dtype=torch.float64, grad_fn=<ReluBackward0>)
tensor(4., dtype=torch.float64, grad_fn=<DotBackward>)
tensor([0., 2., 0.], dtype=torch.float64)
